# -*- coding: utf-8 -*-
#
# saws documentation build configuration file, created by
# sphinx-quickstart on Fri Sep 11 16:09:11 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import s